@url = http://localhost:8080/api/security-clearance
###

//find all   -WORKS

GET {{url}} HTTP/1.1

###

//find by id   -WORKS

GET {{url}}/1 HTTP/1.1

###

//not found by a non-existing id - not working getting a 200//////should get a 404

GET {{url}}/9999 HTTP/1.1

###

//post/create/add security_clearance  WORKS

POST  {{url}} HTTP/1.1
Content-Type: application/json

{
    "name": "Test"

}

###

//post no name   -WORKS with message

POST  {{url}} HTTP/1.1
Content-Type: application/json

{
    "name": " "

}

###

//post duplicate - not working it IS posting duplicate//////should get 400////////////////

POST  {{url}} HTTP/1.1
Content-Type: application/json

{

    "name": "Test"

}

###

//put - 500 - not working  -it should update/////////////////////

PUT  {{url}}/1 HTTP/1.1
Content-Type: application/json

{
    "securityClearanceId" : 1,
    "name": "Test-Update"

}

###

//put no name -500//////////should be a 400 Bad Request//////////////////

PUT  {{url}}/1 HTTP/1.1   ////must have a path variable and match the id in the body
Content-Type: application/json

{

    "securityClearanceId" : 1,
    "name": " "

}

###

//put duplicate - 500 - not working, no message  -should be a 400//////////////////

PUT  {{url}}/1 HTTP/1.1
Content-Type: application/json

{

    "securityClearanceId" : 1,
    "name": "Secret"

}

###

//delete not in use by id   -WORKS 204

DELETE {{url}}/4 HTTP/1.1

###

//delete not found -404 but no message////////////////
DELETE {{url}}/1000 HTTP/1.1

###

//delete in use - 404 ////should be 400  theres also no message//////////////////
DELETE {{url}}/1 HTTP/1.1

###